services:
  backend:
    image: cr.yandex/crpt7qdlb21t83b91iso/flowbit-backend:latest
    container_name: flowbit-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://flowbit:FlowbitStrongPass123!@rc1a-00pdn5dbui9mua0f.mdb.yandexcloud.net:6432/flowbit?sslmode=require
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    image: cr.yandex/crpt7qdlb21t83b91iso/flowbit-frontend:latest
    container_name: flowbit-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://ТВОЙ_PUBLIC_IP:8080/api
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend